name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: dev
      - run: cargo test
  test-full:
    name: StarExec SMT tests
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Install Z3
        uses: pavpanchekha/setup-z3@v0.3.0
        with:
          version: 4.13.0
      - name: Setup rust toolchain, cache
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
      - run: cargo test --release
  benchmarks:
    needs: [test-full]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: 1.76.0
          cache-target: release
          bins: cargo-codspeed

      - name: Build the benchmark target(s)
        run: cargo +1.76.0 codspeed build

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: cargo codspeed run
